name: Makefile CI

on:
  push:
    branches: [ "snowland" ]
  pull_request:
    branches: [ "snowland" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: clone
      run: git clone https://github.com/MizuNotCool/treble_build_nad
      
    - name: cd
      run: cd treble_build_nad

    - name: ls
      run: ls

    - name: Install repo
      run: mkdir ~/bin && PATH=~/bin:$PATH && export PATH
      
    - name: repo check
      run: curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo && chmod a+x ~/bin/repo
      
    - name: Install dependencies
      run: sudo apt update --fix-missing && sudo apt upgrade -y && sudo apt-get install bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev xattr openjdk-11-jdk jq android-sdk-libsparse-utils -y

    - name: build
      run: chmod 777 build.sh && bash build.sh
